### ISSUE TITLE
error on HotspotWizard.turnOnHotspot()

### ISSUE THREAD

**Issue by benzaked** [Pika1998/react-native-wifi-and-hotspot-wizard#3]
hey, 
I'm getting this warning : 
[Unhandled promise rejection: TypeError: null is not an object (evaluating 'RNWifiAndHotspotWizard.turnOffWifi')]
when I'm running the app using expo 
and I'm getting this error when I'm trying to enable hotspot : 
![17c4615b-f639-49d0-80eb-af8e0bb81c41](https://user-images.githubusercontent.com/53477112/86839243-d98b1c00-c0a9-11ea-82ab-3cc8ff8bd9d5.jpg)
Thanks a lot!!

**Comment by Pika1998** [comment]
Hey thank you, but this library doesn't support expo, I have heard that anything that has react-native link doesn't work with expo, I don't think this is a library issue

**Comment by Pika1998** [comment]
But I would love to add expo support to it soon

**Comment by Pika1998** [comment]
https://medium.com/@adhithiravi/building-react-native-apps-expo-or-not-d49770d1f5b8

**Comment by Pika1998** [comment]
@benzaked please let me know if it is not a expo related issue

**Comment by gigabytejayesh** [comment]
Hey @Pika1998 when you are planning to add expo support. We are really looking forward to use this library.

**Comment by Pika1998** [comment]
@gigabytejayesh Thank you, I will try to plan about expo support, it would be great if I had some more contributors who have have some experience about expo and about how expo libraries are developed.
