### ISSUE TITLE
WPA and WPA2 options are not available in hotspot

### ISSUE THREAD

**Issue by DEEPAKSINGHRAGHAV** [Pika1998/react-native-wifi-and-hotspot-wizard#4]
Please add the WPA and WPA2 security while turning on hotspot.

**Comment by Pika1998** [comment]
**Sure**, Thank you!

**Comment by Pika1998** [comment]
**Fixed** in the new release published just now.

![image](https://user-images.githubusercontent.com/36433104/87228820-5f1c0e00-c3c1-11ea-9ca4-a1d666171a28.png)
**_WPA and WPA2 security protocol is enabled by default when Hotspot turns on._**

Thank you @DEEPAKSINGHRAGHAV
