### ISSUE TITLE
Not able to build the project (^1.0.5-stable)

### ISSUE THREAD

**Issue by DEEPAKSINGHRAGHAV** [Pika1998/react-native-wifi-and-hotspot-wizard#7]
^1.0.5-stable issue:
After running the comman react-native run-android. The project buid fails with error:

dModule.java:28: error: package sun.security.ec.point.ProjectivePoint does not exist
import sun.security.ec.point.ProjectivePoint.Mutable;

dModule.java:108: warning: non-varargs call of varargs method with inexact argument type for last parameter;
        int actualState = (Integer) method.invoke(wifi,null);

Execution failed for task ':react-native-wifi-and-hotspot-wizard:compileDebugJavaWithJavac'.

![library](https://user-images.githubusercontent.com/29453884/92639682-cd197e80-f2f9-11ea-9292-1b3c060e89a6.PNG)

**Comment by Pika1998** [comment]
Hey, thank you for opening this issue, I will look into it and let you know

**Comment by Pika1998** [comment]
Please check the react-native version which you are using

**Comment by DEEPAKSINGHRAGHAV** [comment]
I am using "react-native": "0.61.5"

**Comment by Pika1998** [comment]
Can you share a detailed log, in the screenshot I can see 2 errors but unable to make out the error.

**Comment by Pika1998** [comment]
![image](https://user-images.githubusercontent.com/36433104/93707225-2b403000-fb4a-11ea-9c12-559c51a60588.png)

@DEEPAKSINGHRAGHAV  I have made some changes to the build.gradle files and also added automatic build to test the builds.

The builds are showing successful I would like you to test  [**v1.0.6-beta.1**](https://www.npmjs.com/package/react-native-wifi-and-hotspot-wizard) and let me know if your issue is resolved.

**Comment by harshdeep-jft** [comment]
Hi @Pika1998 I have been able make build but, in react native still getting the same error as @DEEPAKSINGHRAGHAV  mention above.

**Comment by Pika1998** [comment]
Hi sorry for the delay, i will look into it and get back to you

**Comment by harshdeep-jft** [comment]
Hi @Pika1998  My issue is resolved. But I wanted to know something about hotspots ,
That in android level above Oreo will there be auto-generated ssid and password , can't I set them manually ?

**Comment by Pika1998** [comment]
I did actually want to do exactly that but for higher Android versions I don't think android allows us to do that.

**Comment by harshdeep-jft** [comment]
I also did some searching for that , but everyone kept saying android restricts to do that.

**Comment by Pika1998** [comment]
Maybe it's a security feature that connections will need action points, like devices can't simply connect to wifi programmatically.

**Comment by harshdeep-jft** [comment]
yes right

**Comment by harshdeep-jft** [comment]
yes ofcourse I would love to.🚀

**Comment by Pika1998** [comment]
Hi @harshdeep-jft , with this can i confirm that we are now able to  build the project in v1.0.6-beta.1 and release it as a stable build?

**Comment by Pika1998** [comment]
Closing this issue as of now

Feel free to re-open  this issue in case anyone feels it is not yet resolved.

**Comment by edcelmanuel** [comment]
![image](https://user-images.githubusercontent.com/82397145/214808455-e739ed21-e438-4296-89c7-a8ef11ddfc5c.png)

**Comment by edcelmanuel** [comment]
got the same error with the version v1.0.6-beta.1

im using "react-native": "0.70.5",
